### ISSUE TITLE
audio_constraints doesn't work

### ISSUE THREAD

**Issue by Jackiexiao** [whitphx/streamlit-webrtc#361]
I try to pass audio constraints to 
```
    media_stream_constraints={
        "video": False,
        "audio": {
            "sampleRate": 16000,
            "sampleSize": 16,
            "noiseSuppression": True,
            "channelCount": 1,
        },
    },
```
but sample_rate is still 48000, why
```
audio_frames = webrtc_ctx.audio_receiver.get_frames(timeout=1)
...
for i, audio_frame in enumerate(audio_frames):
    print(f' frame sample rate {audio_frame.sample_rate}')
# get 48000
```

**Comment by Jackiexiao** [comment]
"noiseSuppression": True, # works by default, I turn it off later because I think it denoise too much 

as for sampleRate, I guess it is because audio track establish with 48k? so I can't change it latter ?

**Comment by whitphx** [comment]
Hi,

Regarding `sampleRate`, it might be unchangeable.
[This article](https://blog.addpipe.com/audio-constraints-getusermedia/), though it's bit old, says `sampleRate` is fixed in all browsers.

Thank you very much for the informative figure about the experiment on `echoCancellation` and `noiseSuppression`!
