### ISSUE TITLE
Access device information

### ISSUE THREAD

**Issue by jay-karimi** [whitphx/streamlit-webrtc#744]
The webrtc UI allows the user to select a device. I'm wondering if there is a way to access the selected devices information (e.g. name, serial number, etc)?

**Comment by whitphx** [comment]
It is not supported for now.

Currently, the device info is gathered and processed only on the client-side, and not sent to the server-side.
It's technically possible to change it to send the info to the server so that the server-side Python code can access it, however, I don't want to do it because I think we should restrict the types and amount of information sent to the server in order to avoid unexpected leak or any other vulnerabilities.
